### ISSUE TITLE
转换执行正常，但编号错误

### ISSUE THREAD

**Issue by zackyjc** [liuhao326/pythontools#2]
我有一篇章节上百的参考资料，正需要这个工具，谢谢！

但是转换完成后有编号不对，如下：

问题1:
```
### 9.19.3 Query Parameters
### 9.19.4 Response
## 9.110 Replace Status       ----> 应该是：## 9.20， 但现在是：## 9.110
### 9.110.1 HTTP Request
```

问题2:
```
### 9.114.5 Response         ---> 应该是 ### 9.24.5
### 9.1114.5 aaa                  --->             ### 9.34.5
# 10. ReplicationController v1 core
## 10..1 ReplicationControllerSpec v1 core   ---> 应该是：## 10.1，多了个点
...
# 10. xxxxx                           ---> 大于10章的标题后，所有一级标题都停在 10.
## 10..1 yyyy   

# 10. zzzzz
## 10..1 zzzz
...

## 10..111111111111111111111113 title


```

**Comment by liuhao326** [comment]
请问方便将目录发给我吗？目录截图也可以。

**Comment by zackyjc** [comment]
Hi liuhao,
   附件是一个完整的目录清单，左边是一个工具显示的正确编码，右边紧挨着是工具的编码输出，可以帮助您检查。


| |
zackyjc
|
|
zackyjc@163.com
|
签名由网易邮箱大师定制


在2020年05月26日 23:53，liuhao326<notifications@github.com> 写道：

请问方便将目录发给我吗？目录截图也可以。

**Comment by zackyjc** [comment]
这个目录只有三级：# ## ###，就是比较长，你可以方便构造个比较长的目录清单验证。
章节编码：
A.B.C


A>10 出现 10…
B,C>19 几十就出现几个连续的1， 112 就是 22






| |
zackyjc
|
|
zackyjc@163.com
|
签名由网易邮箱大师定制


在2020年05月26日 23:53，liuhao326<notifications@github.com> 写道：

请问方便将目录发给我吗？目录截图也可以。

**Comment by liuhao326** [comment]
> 这个目录只有三级：# ## ###，就是比较长，你可以方便构造个比较长的目录清单验证。 章节编码： A.B.C A>10 出现 10… B,C>19 几十就出现几个连续的1， 112 就是 22 | | zackyjc | | zackyjc@163.com | 签名由网易邮箱大师定制 在2020年05月26日 23:53，liuhao326<notifications@github.com> 写道： 请问方便将目录发给我吗？目录截图也可以。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

重新下载再试一下，应该没问题了。

**Comment by zackyjc** [comment]
命令不能结束，没有输出文件，你试试附件的标题文件？
[toc.md.zip](https://github.com/liuhao326/pythontools/files/4686588/toc.md.zip)

**Comment by liuhao326** [comment]
> 命令不能结束，没有输出文件，你试试附件的标题文件？
> [toc.md.zip](https://github.com/liuhao326/pythontools/files/4686588/toc.md.zip)

应该没问题了，你再试试。

**Comment by zackyjc** [comment]
Great work!

**Comment by liuhao326** [comment]
> Great work!

嗯，多谢反馈
